
/* -------------- Hangman words ----------------*/

exports.hangmanWords = {
	"Paises": ['Mexico','España','Irlanda','Japon','China','Tailandia','Finlandia','Argentina','Colombia','Brasil','Dubai','Egipto','Pais Vasco','Islas Canarias','Rumania','Madagascar','Afganistan','Alemania','Papua Nueva Guinea','Noruega','Puerto Rico','Sahara Occidental','Singapur','Trinidad y Tobago','Reino Unido','Nagorno Karabaj','Malasia'],
	"Animales": ['Lechuza','Aguila Real','Bisonte','Elefante','Guepardo','Jaguar','Rinoceronte','Estrella De Mar','Delfin','Renacuajo','Salamandra','Narval','Elefante Marino','Carpincho','Murcielago','Anaconda','Pelicano','Cangrejo','Mariposa','Dragon de Komodo','Escarabajo','Cienpies','Tortuga','Comadreja','Zarigueya'],
	"Baile": ['Bachata', 'Ballet', 'Breakdancing', 'Contemporneo', 'Country', 'Cumbia', 'Disco', 'Duranguense', 'Electro', 'Fandango', 'Flamenco', 'Freestyle', 'Gangnam Style', 'Grinding', 'Hardcore', 'Harlem Shake', 'Hip hop', 'Jarabe tapatio', 'Jazz', 'Jumpstyle', 'K-pop', 'Lambada', 'Limbo', 'Macarena', 'Mambo', 'Marimba', 'Merengue', 'Polka', 'Quebradita', 'Reggaeton', 'Rock and Roll', 'Rumba', 'Salsa', 'Samba', 'Shuffle', 'Tango', 'Tap Dance', 'Tecktonik', 'Twerking', 'Twist', 'Vals', 'YMCA', 'Zamba', 'Zapateado', 'Zumba'],
	"Pokemon Showdown": ['Tier', 'Over Used', 'Under Used', 'Rarely Used', 'Never Used', 'Ubers', 'Little Cup', 'Seasonal Battles', 'Random Battle', 'Sken', 'INSANE LOVER', 'Astyanax', 'Gorka Morrison', 'xJoelituh', 'Iyarito', 'Lost Seso', 'Zarel', 'Gatto', 'Kek', 'AminitraBoTTT', 'Sken', 'Iyarito', 'Alastor Law', 'Joim','Nathaniel Ayers','Daiquiri','Slayer95','Jasmine','chaos'],
	"Frutas": ['Arandano', 'Cereza', 'Frambuesa', 'Fresa', 'Grosella', 'Guinda', 'Zarzamora', 'Mora Azul', 'Coco', 'Aceituna', 'Manzana', 'Uva', 'Limon', 'Lima', 'Naranja', 'Toronja', 'Durazno', 'Guayaba', 'Piña', 'Kiwi', 'Papaya', 'Melon', 'Melocoton', 'Ciruela'],
	"Vegetales": ['Berenjena', 'Calabacin', 'Calabaza', 'Cebolla', 'Tomate', 'Apio', 'Acelga', 'Espinaca', 'Pepinillo', 'Champiñon', 'Pimiento', 'Alcachofa', 'Brocoli', 'Coliflor', 'Lechuga', 'Patata', 'Boniato', 'Nabo', 'Rabano', 'Zanahoria', 'Mandioca', 'Soja', 'Guisantes', 'Habas', 'Remolacha'],
	"Animes": ['Dragon Ball', 'Ranma', 'Pretty Cure', 'Doraemon', 'Sinchan', 'Deadman Wonderland', 'Kill La Kill', 'Naruto', 'Bleach', 'Sword Art Online', 'Mirai Nikki', 'Guilty Crown', 'Fairy Tail', 'Zatch Bell', 'Pokemon', 'Beyblade', 'Hunter x Hunter', 'Soul Eater', 'Inuyasha', 'The Prince Of Tennis'],
	"Paginas Web": ['facebook', 'amazon', 'google', 'ebay', 'youtube', 'instagram', 'hotmail', 'yahoo', 'wikipedia', 'twitter', 'my space', 'badoo', 'gmail', 'ask', 'pastebin', 'showdown', 'mercadolibre', 'mediafire', 'rapid share', 'taringa', 'softonic', 'hastebin', 'marca', 'skype'],
	"Marcas": ['adidas', 'nike', 'vanz', 'hugo boss', 'calvin klein', 'supra', 'converse', 'coca cola', 'oreo', 'mc donald', 'nokia', 'iphone', 'motorola', 'movistar', 'disney', 'gillette', 'sony', 'toyota', 'microsoft', 'canon', 'ferrari', 'siemens', 'samsung', 'pepsi', 'kelloggs','Colgate', 'Palmolive', 'Snicker', 'SubWay', 'Burger King','Victoria Secret','Sony', 'Nokia', 'Sega', 'Starbucks','Nike','Carolina Herrera','Georgio Armani', 'Maruchan', 'Nissin', 'Visa', 'Pepsi', 'Android', 'Apple', 'Windows Phone', 'Red Bull'],
	"Deportes": ['atletismo','remo','badminton', 'baloncesto', 'boxeo', 'canotaje', 'ciclismo', 'ecuestre', 'esgrima', 'futbol', 'gimnasia', 'halterofilia', 'balonmano', 'hockey', 'judo', 'natacion', 'pentatlon moderno', 'taekwondo', 'tenis', 'tenis de mesa', 'tiro', 'tiro con arco', 'triatlon','vela','voleibol'],
	"Personajes Anime de Pokemon": ['Ash', 'Misty', 'Brock', 'May', 'Dawn', 'Jessie', 'James', 'Joy', 'Mara', 'Tracey', 'Oak', 'Rojo', 'Cintia', 'Maximo', 'Mirto', 'Gary', 'Lance', 'Diantha', 'Iris', 'Clemont', 'Serena', 'Paul', 'Barry', 'Drew', 'Millo'],
	"Estilos Pokemon Competitivo": ['Offense', 'Stall', 'Balanced', 'Dragmag', 'Semistall', 'Volt Turn', 'Weather'],
	"Celebridades": ["Adam Sandler", "Amy Winehouse", "Ariana Grande", "Bruno Mars", "Salma Hayek", "Will Smith", "Alyson Michalka", "Miley Cyrus", "Taylor Swift", "Kevin James", "Taylor Lautner", "Zac Efron", "Ashley Tisdale", "Ashton Kutcher", "Jennifer Aniston", "Cameron Diaz", "Brenda Asnicar", "Brenda Song", "Arnold Schwarzenegger", "Jamie Lee Curtis", "Eddie Murphy", "Shannen Doherty", "Emma Watson", "Nicole Kidman", "Meg Ryan", "Nicholas Cage", "Anna Nicole Smith", "Marilyn Monroe", "Brad Pitt", "Angelina Jolie", "Anne Hathaway", "Vanessa Hudgens", "Vin Diesel", "Paul Walker", "Whitney Houston", "Silvester Stallone", "Robin Williams", "Dakota Fanning", "Denzel Washington", "Jim Carrey", "Bruce Willis", "Pamela Anderson", "Carmen Electra", "Kim Kardashian", "Dwayne Johnson"],
	"VideoJuegos Pokemon": ['Rojo', 'Azul', 'Amarillo', 'Verde', 'Oro', 'Plata', 'Cristal', 'Esmeralda', 'Zafiro', 'Rubi', 'Rojo Fuego', 'Verde Hoja', 'Perla', 'Diamante', 'Platino', 'Heart Gold', 'Soul Silver', 'Negro', 'Blanco', 'Negro 2', 'Blanco 2', 'X', 'Y', 'Alfa Zafiro', 'Omega Rubi', 'Pinball','Stadium','Ranger','Mystery Dungeon','Puzzle Challenge','Puzzle League','Trozei','Stadium 2','Colosseum','Battle Revolution','XD Tempestad Oscura','PokePark','Rumble'],
	"Servidores de PS": ['Pandora', 'Viridian', 'Nimbus', 'Infinite', 'Oasis', 'Smogon Tournaments', 'PokeCommunity', 'Pokestrat', 'Reborn', 'Gold', 'Core', 'Battle Tower', 'Parukia', 'Aqua', 'French Time', 'Pokebeach', 'Lumen', 'Indigo']
};
