exports.trad = {
	"ability": [
		{"en": "Water Absorb", "es": "Absor. agua"},
		{"en": "Volt Absorb", "es": "Absor. elec."},
		{"en": "Flash Fire", "es": "Absor. fuego"},
		{"en": "Cloud Nine", "es": "Aclimatación"},
		{"en": "Guts", "es": "Agallas"},
		{"en": "Battle Armor", "es": "Armad. bat."},
		{"en": "Truant", "es": "Ausente"},
		{"en": "Air Lock", "es": "Bucle aire"},
		{"en": "Rock Head", "es": "Cabeza roca"},
		{"en": "Cacophony", "es": "Cacofonía"},
		{"en": "Color Change", "es": "Cambio color"},
		{"en": "Shell Armor", "es": "Caparazón"},
		{"en": "Sand Stream", "es": "Chorro arena"},
		{"en": "Chlorophyll", "es": "Clorofila"},
		{"en": "Hyper Cutter", "es": "Corte fuerte"},
		{"en": "Flame Body", "es": "Cuerpo llama"},
		{"en": "Clear Body", "es": "Cuerpo puro"},
		{"en": "Rain Dish", "es": "Cura lluvia"},
		{"en": "Natural Cure", "es": "Cura natural"},
		{"en": "Oblivious", "es": "Despiste"},
		{"en": "Serene Grace", "es": "Dicha"},
		{"en": "Effect Spore", "es": "Efec. espora"},
		{"en": "Static", "es": "Elec. estát."},
		{"en": "Pure Power", "es": "Energía pura"},
		{"en": "Swarm", "es": "Enjambre"},
		{"en": "Hustle", "es": "Entusiasmo"},
		{"en": "Marvel Scale", "es": "Escama esp."},
		{"en": "Magma Armor", "es": "Escudo magma"},
		{"en": "Overgrow", "es": "Espesura"},
		{"en": "Vital Spirit", "es": "Espír. vital"},
		{"en": "Limber", "es": "Flexibilidad"},
		{"en": "Inner Focus", "es": "Foco interno"},
		{"en": "Run Away", "es": "Fuga"},
		{"en": "Cute Charm", "es": "Gran encanto"},
		{"en": "Stench", "es": "Hedor"},
		{"en": "Damp", "es": "Humedad"},
		{"en": "White Smoke", "es": "Humo blanco"},
		{"en": "Illuminate", "es": "Iluminación"},
		{"en": "Speed Boost", "es": "Impulso"},
		{"en": "Magnet Pull", "es": "Imán"},
		{"en": "Immunity", "es": "Inmunidad"},
		{"en": "Insomnia", "es": "Insomnio"},
		{"en": "Soundproof", "es": "Insonorizar"},
		{"en": "Intimidate", "es": "Intimidación"},
		{"en": "Levitate", "es": "Levitación"},
		{"en": "Drizzle", "es": "Llovizna"},
		{"en": "Liquid Ooze", "es": "Lodo líquido"},
		{"en": "Early Bird", "es": "Madrugar"},
		{"en": "Blaze", "es": "Mar llamas"},
		{"en": "Plus", "es": "Más"},
		{"en": "Minus", "es": "Menos"},
		{"en": "Shed Skin", "es": "Mudar"},
		{"en": "Swift Swim", "es": "Nado rápido"},
		{"en": "Compoundeyes", "es": "Ojocompuesto"},
		{"en": "Lightningrod", "es": "Pararrayos"},
		{"en": "Rough Skin", "es": "Piel tosca"},
		{"en": "Shield Dust", "es": "Polvo escudo"},
		{"en": "Huge Power", "es": "Potencia"},
		{"en": "Forecast", "es": "Predicción"},
		{"en": "Pressure", "es": "Presión"},
		{"en": "Poison Point", "es": "Punto tóxico"},
		{"en": "Trace", "es": "Rastro"},
		{"en": "Pickup", "es": "Recogida"},
		{"en": "Own Tempo", "es": "Ritmo propio"},
		{"en": "Sturdy", "es": "Robustez"},
		{"en": "Thick Fat", "es": "Sebo"},
		{"en": "Drought", "es": "Sequía"},
		{"en": "Synchronize", "es": "Sincronía"},
		{"en": "Shadow Tag", "es": "Sombratrampa"},
		{"en": "Wonder Guard", "es": "Superguarda"},
		{"en": "Torrent", "es": "Torrente"},
		{"en": "Arena Trap", "es": "Trampa arena"},
		{"en": "Water Veil", "es": "Velo agua"},
		{"en": "Sand Veil", "es": "Velo arena"},
		{"en": "Suction Cups", "es": "Ventosas"},
		{"en": "Sticky Hold", "es": "Viscosidad"},
		{"en": "Keen Eye", "es": "Vista lince"},
		{"en": "Adaptability", "es": "Adaptable"},
		{"en": "Super Luck", "es": "Afortunado"},
		{"en": "Forewarn", "es": "Alerta"},
		{"en": "Anticipation", "es": "Anticipación"},
		{"en": "Poison Heal", "es": "Antídoto"},
		{"en": "Reckless", "es": "Audaz"},
		{"en": "Frisk", "es": "Cacheo"},
		{"en": "Storm Drain", "es": "Colector"},
		{"en": "Tinted Lens", "es": "Cromolente"},
		{"en": "Leaf Guard", "es": "Defensa hoja"},
		{"en": "Download", "es": "Descarga"},
		{"en": "Flower Gift", "es": "Don floral"},
		{"en": "Motor Drive", "es": "Electromotor"},
		{"en": "Skill Link", "es": "Encadenado"},
		{"en": "Technician", "es": "Experto"},
		{"en": "Filter", "es": "Filtro"},
		{"en": "Sniper", "es": "Francotirador"},
		{"en": "Gluttony", "es": "Gula"},
		{"en": "Ice Body", "es": "Gélido"},
		{"en": "Hydration", "es": "Hidratación"},
		{"en": "Heatproof", "es": "Ignífugo"},
		{"en": "Unaware", "es": "Ignorante"},
		{"en": "Steadfast", "es": "Impasible"},
		{"en": "No Guard", "es": "Indefenso"},
		{"en": "Slow Start", "es": "Inicio lento"},
		{"en": "Scrappy", "es": "Intrépido"},
		{"en": "Anger Point", "es": "Irascible"},
		{"en": "Unburden", "es": "Liviano"},
		{"en": "Bad dreams", "es": "Mal sueño"},
		{"en": "Snow Cloak", "es": "Manto níveo"},
		{"en": "Multitype", "es": "Multitipo"},
		{"en": "Magic Guard", "es": "Muro mágico"},
		{"en": "Snow Warning", "es": "Nevada"},
		{"en": "Normalize", "es": "Normalidad"},
		{"en": "Dry Skin", "es": "Piel seca"},
		{"en": "Quick Feet", "es": "Pies rápidos"},
		{"en": "Solar Power", "es": "Poder solar"},
		{"en": "Iron Fist", "es": "Puño férreo"},
		{"en": "Honey Gather", "es": "Recogemiel"},
		{"en": "Aftermath", "es": "Resquicio"},
		{"en": "Stall", "es": "Rezagado"},
		{"en": "Rivalry", "es": "Rivalidad"},
		{"en": "Solid Rock", "es": "Roca sólida"},
		{"en": "Mold Breaker", "es": "Rompemoldes"},
		{"en": "Simple", "es": "Simple"},
		{"en": "Tangled Feet", "es": "Tumbos"},
		{"en": "Klutz", "es": "Zoquete"},
		{"en": "Infiltrator", "es": "Allanamiento"},
		{"en": "Healer", "es": "Alma cura"},
		{"en": "Weak Armor", "es": "Armadura frágil"},
		{"en": "Moxie", "es": "Autoestima"},
		{"en": "Prankster", "es": "Bromista"},
		{"en": "Analytic", "es": "Cálculo final"},
		{"en": "Rattled", "es": "Cobardía"},
		{"en": "Multiscale", "es": "Compensación"},
		{"en": "Defiant", "es": "Competitivo"},
		{"en": "Friend Guard", "es": "Compiescolta"},
		{"en": "Harvest", "es": "Cosecha"},
		{"en": "Cursed Body", "es": "Cuerpo maldito"},
		{"en": "Magic Bounce", "es": "Espejo mágico"},
		{"en": "Defeatist", "es": "Flaqueza"},
		{"en": "Overcoat", "es": "Funda"},
		{"en": "Sap Sipper", "es": "Herbívoro"},
		{"en": "Pickpocket", "es": "Hurto"},
		{"en": "Illusion", "es": "Ilusión"},
		{"en": "Flare Boost", "es": "Ímpetu ardiente"},
		{"en": "Sand Rush", "es": "Ímpetu arena"},
		{"en": "Toxic Boost", "es": "Ímpetu tóxico"},
		{"en": "Imposter", "es": "Impostor"},
		{"en": "Justified", "es": "Justiciero"},
		{"en": "Light Metal", "es": "Metal liviano"},
		{"en": "Heavy Metal", "es": "Metal pesado"},
		{"en": "Zen Mode", "es": "Modo Daruma"},
		{"en": "Mummy", "es": "Momia"},
		{"en": "Unnerve", "es": "Nerviosismo"},
		{"en": "Wonder Skin", "es": "Piel milagro"},
		{"en": "Sand Force", "es": "Poder arena"},
		{"en": "Sheer Force", "es": "Potencia bruta"},
		{"en": "Iron Barbs", "es": "Punta acero"},
		{"en": "Regenerator", "es": "Regeneración"},
		{"en": "Contrary", "es": "Respondón"},
		{"en": "Big Pecks", "es": "Sacapecho"},
		{"en": "Telepathy", "es": "Telepatía"},
		{"en": "Teravolt", "es": "Terravoltaje"},
		{"en": "Victory Star", "es": "Tinovictoria"},
		{"en": "Poison Touch", "es": "Toque tóxico"},
		{"en": "Turboblaze", "es": "Turbollama"},
		{"en": "Moody", "es": "Veleta"},
		{"en": "Gale Wings", "es": "Alas vendaval"},
		{"en": "Bulletproof", "es": "Antibalas"},
		{"en": "Parental Bond", "es": "Amor filial"},
		{"en": "Fairy Aura", "es": "Aura feérica"},
		{"en": "Dark Aura", "es": "Aura oscura"},
		{"en": "Gooey", "es": "Baba"},
		{"en": "Stance Change", "es": "Cambio táctico"},
		{"en": "Cheek Pouch", "es": "Carrillo"},
		{"en": "Tough Claws", "es": "Garra dura"},
		{"en": "Primordial Sea", "es": "Mar del albor"},
		{"en": "Mega Launcher", "es": "Megadisparador"},
		{"en": "Strong Jaw", "es": "Mandíbula fuerte"},
		{"en": "Grass Pelt", "es": "Manto frondoso"},
		{"en": "Protean", "es": "Mutatipo"},
		{"en": "Fur Coat", "es": "Pelaje recio"},
		{"en": "Aerilate", "es": "Piel celeste"},
		{"en": "Pixilate", "es": "Piel feérica"},
		{"en": "Refrigerate", "es": "Piel helada"},
		{"en": "Magician", "es": "Prestidigitador"},
		{"en": "Delta Stream", "es": "Ráfaga delta"},
		{"en": "Aura break", "es": "Rompeaura"},
		{"en": "Symbiosis", "es": "Simbiosis"},
		{"en": "Competitive", "es": "Tenacidad"},
		{"en": "Desolate Land", "es": "Tierra del ocaso"},
		{"en": "Aroma Veil", "es": "Velo aroma"},
		{"en": "Sweet Veil", "es": "Velo dulce"},
		{"en": "Flower Veil", "es": "Velo flor"}
	],
	"move": [
		{"en": "Close Combat", "es": "A bocajarro"},
		{"en": "Defend Order", "es": "A defender"},
		{"en": "Worry Seed", "es": "Abatidoras"},
		{"en": "Absorb", "es": "Absorber"},
		{"en": "Acid", "es": "Ácido"},
		{"en": "Infestation", "es": "Acoso"},
		{"en": "Acrobatics", "es": "Acróbata"},
		{"en": "Aqua Ring", "es": "Acua aro"},
		{"en": "Aqua Tail", "es": "Acua cola"},
		{"en": "Aqua Jet", "es": "Acua jet"},
		{"en": "Acupressure", "es": "Acupresión"},
		{"en": "Nature power", "es": "Adaptación"},
		{"en": "Aeroblast", "es": "Aerochorro"},
		{"en": "Hone Claws", "es": "Afilagarras"},
		{"en": "Sharpen", "es": "Afilar"},
		{"en": "Vice Grip", "es": "Agarre"},
		{"en": "Crush Grip", "es": "Agarrón"},
		{"en": "Agility", "es": "Agilidad"},
		{"en": "Muddy water", "es": "Agua lodosa"},
		{"en": "Endure", "es": "Aguante"},
		{"en": "Fell Stinger", "es": "Aguijón letal"},
		{"en": "Air cutter", "es": "Aire afilado"},
		{"en": "Attack Order", "es": "Al ataque"},
		{"en": "Steel wing", "es": "Ala de acero"},
		{"en": "Oblivion Wing", "es": "Ala mortífera"},
		{"en": "Snarl", "es": "Alarido"},
		{"en": "Uproar", "es": "Alboroto"},
		{"en": "Autotomize", "es": "Aligerar"},
		{"en": "Refresh", "es": "Alivio"},
		{"en": "Avalanche", "es": "Alud"},
		{"en": "Feint", "es": "Amago"},
		{"en": "Amnesia", "es": "Amnesia"},
		{"en": "Soft-boiled", "es": "Amortiguador"},
		{"en": "Soak", "es": "Anegar"},
		{"en": "Blast burn", "es": "Anillo ígneo"},
		{"en": "Smack Down", "es": "Antiaéreo"},
		{"en": "Quick Guard", "es": "Anticipo"},
		{"en": "Heal Block", "es": "Anticura"},
		{"en": "Covet", "es": "Antojo"},
		{"en": "Disable", "es": "Anulación"},
		{"en": "Scratch", "es": "Arañazo"},
		{"en": "Head Charge", "es": "Ariete"},
		{"en": "Acid armor", "es": "Armadura ácida"},
		{"en": "Aromatherapy", "es": "Aromaterapia"},
		{"en": "Ingrain", "es": "Arraigo"},
		{"en": "Heart Stamp", "es": "Arrumaco"},
		{"en": "Trump Card", "es": "As oculto"},
		{"en": "Dragon Ascent", "es": "Ascenso draco"},
		{"en": "Ember", "es": "Ascuas"},
		{"en": "Horn Leech", "es": "Asta drenaje"},
		{"en": "Bind", "es": "Atadura"},
		{"en": "Sky attack", "es": "Ataque aéreo"},
		{"en": "Wing attack", "es": "Ataque ala"},
		{"en": "Sand Attack", "es": "Ataque arena"},
		{"en": "Bolt Strike", "es": "Ataque fulgor"},
		{"en": "Fury attack", "es": "Ataque furia"},
		{"en": "Bone rush", "es": "Ataque óseo"},
		{"en": "Quick attack", "es": "Ataque rápido"},
		{"en": "Slam", "es": "Atizar"},
		{"en": "Attract", "es": "Atracción"},
		{"en": "Howl", "es": "Aullido"},
		{"en": "Magnetic Flux", "es": "Aura magnética"},
		{"en": "Self-destruct", "es": "Autodestrucción"},
		{"en": "Heal Order", "es": "Auxilio"},
		{"en": "Rock slide", "es": "Avalancha"},
		{"en": "Work Up", "es": "Avivar"},
		{"en": "Assist", "es": "Ayuda"},
		{"en": "Flail", "es": "Azote"},
		{"en": "Barrier", "es": "Barrera"},
		{"en": "Spiky Shield", "es": "Barrera espinosa"},
		{"en": "Milk drink", "es": "Batido"},
		{"en": "Lovely kiss", "es": "Beso amoroso"},
		{"en": "Draining kiss", "es": "Beso drenaje"},
		{"en": "Sweet kiss", "es": "Beso dulce"},
		{"en": "Gastro Acid", "es": "Bilis"},
		{"en": "Block", "es": "Bloqueo"},
		{"en": "Mud-slap", "es": "Bofetón lodo"},
		{"en": "Ice ball", "es": "Bola hielo"},
		{"en": "Mist ball", "es": "Bola neblina"},
		{"en": "Shadow ball", "es": "Bola sombra"},
		{"en": "Electro Ball", "es": "Bola voltio"},
		{"en": "Acid Spray", "es": "Bomba ácida"},
		{"en": "Mud Bomb", "es": "Bomba fango"},
		{"en": "Seed Bomb", "es": "Bomba germen"},
		{"en": "Egg bomb", "es": "Bomba huevo"},
		{"en": "Searing Shot", "es": "Bomba ígnea"},
		{"en": "Magnet Bomb", "es": "Bomba imán"},
		{"en": "Sludge bomb", "es": "Bomba lodo"},
		{"en": "Sonic Boom", "es": "Bomba sónica"},
		{"en": "Yawn", "es": "Bostezo"},
		{"en": "Bounce", "es": "Bote"},
		{"en": "Needle arm", "es": "Brazo pincho"},
		{"en": "Dark Void", "es": "Brecha negra"},
		{"en": "Dazzling Gleam", "es": "Brillo mágico"},
		{"en": "Dive", "es": "Buceo"},
		{"en": "Sand tomb", "es": "Bucle arena"},
		{"en": "Assurance", "es": "Buena baza"},
		{"en": "Bubble", "es": "Burbuja"},
		{"en": "Iron Head", "es": "Cabeza de hierro"},
		{"en": "Skull bash", "es": "Cabezazo"},
		{"en": "Zen Headbutt", "es": "Cabezazo zen"},
		{"en": "Incinerate", "es": "Calcinación"},
		{"en": "Play Nice", "es": "Camaradería"},
		{"en": "Heart Swap", "es": "Cambia almas"},
		{"en": "Guard Swap", "es": "Cambia defensa"},
		{"en": "Power Swap", "es": "Cambia fuerza"},
		{"en": "Ally Switch", "es": "Cambio banda"},
		{"en": "Shift Gear", "es": "Cambio de marcha"},
		{"en": "Flatter", "es": "Camelo"},
		{"en": "Heal bell", "es": "Campana cura"},
		{"en": "Grassy Terrain", "es": "Campo de hierba"},
		{"en": "Misty Terrain", "es": "Campo de niebla"},
		{"en": "Electric Terrain", "es": "Campo eléctrico"},
		{"en": "Camouflage", "es": "Camuflaje"},
		{"en": "Round", "es": "Canon"},
		{"en": "Sing", "es": "Canto"},
		{"en": "Relic Song", "es": "Canto arcaico"},
		{"en": "Ice Shard", "es": "Canto helado"},
		{"en": "Perish song", "es": "Canto mortal"},
		{"en": "Magic coat", "es": "Capa mágica"},
		{"en": "Scary face", "es": "Cara susto"},
		{"en": "Icicle spear", "es": "Carámbano"},
		{"en": "Play Rough", "es": "Carantoña"},
		{"en": "Charge", "es": "Carga"},
		{"en": "Dragon Rush", "es": "Carga dragón"},
		{"en": "Parabolic Charge", "es": "Carga parábola"},
		{"en": "Venoshock", "es": "Carga tóxica"},
		{"en": "Sky Drop", "es": "Caída libre"},
		{"en": "Waterfall", "es": "Cascada"},
		{"en": "Punishment", "es": "Castigo"},
		{"en": "After You", "es": "Cede paso"},
		{"en": "Celebrate", "es": "Celebración"},
		{"en": "Imprison", "es": "Cerca"},
		{"en": "Fairy Lock", "es": "Cerrojo feérico"},
		{"en": "Chatter", "es": "Cháchara"},
		{"en": "Mud sport", "es": "Chapoteo lodo"},
		{"en": "Screech", "es": "Chirrido"},
		{"en": "Spark", "es": "Chispa"},
		{"en": "Discharge", "es": "Chispazo"},
		{"en": "Steam Eruption", "es": "Chorro de vapor"},
		{"en": "Leech life", "es": "Chupavidas"},
		{"en": "Icicle Crash", "es": "Chuzos"},
		{"en": "Twister", "es": "Ciclón"},
		{"en": "Leaf Tornado", "es": "Ciclón de hojas"},
		{"en": "Spike cannon", "es": "Clavo cañón"},
		{"en": "Hold Back", "es": "Clemencia"},
		{"en": "Reflect Type", "es": "Clonatipo"},
		{"en": "Dragon Tail", "es": "Cola dragón"},
		{"en": "Iron tail", "es": "Cola férrea"},
		{"en": "Poison tail", "es": "Cola veneno"},
		{"en": "Ice Fang", "es": "Colmillo hielo"},
		{"en": "Fire Fang", "es": "Colmillo ígneo"},
		{"en": "Thunder Fang", "es": "Colmillo rayo"},
		{"en": "Poison fang", "es": "Colmillo veneno"},
		{"en": "Dream eater", "es": "Come sueños"},
		{"en": "Draco Meteor", "es": "Cometa draco"},
		{"en": "Razor Shell", "es": "Concha filo"},
		{"en": "Forest's Curse", "es": "Condena silvana"},
		{"en": "Confide", "es": "Confidencia"},
		{"en": "Confusion", "es": "Confusión"},
		{"en": "Lucky Chant", "es": "Conjuro"},
		{"en": "Wrap", "es": "Constricción"},
		{"en": "Swagger", "es": "Contoneo"},
		{"en": "Counter", "es": "Contraataque"},
		{"en": "Conversion", "es": "Conversión"},
		{"en": "Conversion 2", "es": "Conversión 2"},
		{"en": "Copycat", "es": "Copión"},
		{"en": "Horn attack", "es": "Cornada"},
		{"en": "Bulk up", "es": "Corpulencia"},
		{"en": "Cut", "es": "Corte"},
		{"en": "Fury cutter", "es": "Corte furia"},
		{"en": "Spacial Rend", "es": "Corte vacío"},
		{"en": "Ion Deluge", "es": "Cortina plasma"},
		{"en": "Tickle", "es": "Cosquillas"},
		{"en": "Slash", "es": "Cuchillada"},
		{"en": "Heavy Slam", "es": "Cuerpo pesado"},
		{"en": "Quiver Dance", "es": "Danza aleteo"},
		{"en": "Entrainment", "es": "Danza amiga"},
		{"en": "Teeter dance", "es": "Danza caos"},
		{"en": "Dragon dance", "es": "Danza dragón"},
		{"en": "Swords dance", "es": "Danza espada"},
		{"en": "Fiery Dance", "es": "Danza llama"},
		{"en": "Rain dance", "es": "Danza lluvia"},
		{"en": "Lunar Dance", "es": "Danza lunar"},
		{"en": "Petal dance", "es": "Danza pétalo"},
		{"en": "Feather Dance", "es": "Danza pluma"},
		{"en": "Secret power", "es": "Daño secreto"},
		{"en": "Iron defense", "es": "Defensa férrea"},
		{"en": "Flower Shield", "es": "Defensa floral"},
		{"en": "Brick break", "es": "Demolición"},
		{"en": "Take down", "es": "Derribo"},
		{"en": "Knock off", "es": "Desarme"},
		{"en": "Growth", "es": "Desarrollo"},
		{"en": "Rest", "es": "Descanso"},
		{"en": "Rollout", "es": "Desenrollar"},
		{"en": "Wish", "es": "Deseo"},
		{"en": "Healing Wish", "es": "Deseo cura"},
		{"en": "Doom desire", "es": "Deseo oculto"},
		{"en": "Glare", "es": "Deslumbrar"},
		{"en": "Defog", "es": "Despejar"},
		{"en": "Revenge", "es": "Desquite"},
		{"en": "Flash", "es": "Destello"},
		{"en": "Pound", "es": "Destructor"},
		{"en": "Detect", "es": "Detección"},
		{"en": "Pay day", "es": "Día de pago"},
		{"en": "Sunny day", "es": "Día soleado"},
		{"en": "String shot", "es": "Disparo demora"},
		{"en": "Mirror Shot", "es": "Disparo espejo"},
		{"en": "Mud shot", "es": "Disparo lodo"},
		{"en": "Roar Of Time", "es": "Distorsión"},
		{"en": "Pain split", "es": "Divide dolor"},
		{"en": "Twineedle", "es": "Doble ataque"},
		{"en": "Double slap", "es": "Doble bofetón"},
		{"en": "Double team", "es": "Doble equipo"},
		{"en": "Double-edge", "es": "Doble filo"},
		{"en": "Double Hit", "es": "Doble golpe"},
		{"en": "Double kick", "es": "Doble patada"},
		{"en": "Signal beam", "es": "Doble rayo"},
		{"en": "Natural Gift", "es": "Don natural"},
		{"en": "Dragon breath", "es": "Dragoaliento"},
		{"en": "Leech seed", "es": "Drenadoras"},
		{"en": "Sweet scent", "es": "Dulce aroma"},
		{"en": "Metal sound", "es": "Eco metálico"},
		{"en": "Echoed Voice", "es": "Eco voz"},
		{"en": "Electrify", "es": "Electrificación"},
		{"en": "Zap cannon", "es": "Electrocañón"},
		{"en": "Electroweb", "es": "Electrotela"},
		{"en": "Embargo", "es": "Embargo"},
		{"en": "Arm thrust", "es": "Empujón"},
		{"en": "Charm", "es": "Encanto"},
		{"en": "Energy Ball", "es": "Energibola"},
		{"en": "Outrage", "es": "Enfado"},
		{"en": "Coil", "es": "Enrosque"},
		{"en": "Flare Blitz", "es": "Envite ígneo"},
		{"en": "Belch", "es": "Eructo"},
		{"en": "Scald", "es": "Escaldar"},
		{"en": "King's Shield", "es": "Escudo real"},
		{"en": "Mat Block", "es": "Escudo tatami"},
		{"en": "Spit up", "es": "Escupir"},
		{"en": "Aura Sphere", "es": "Esfera aural"},
		{"en": "Endeavor", "es": "Esfuerzo"},
		{"en": "Wake-up Slap", "es": "Espabila"},
		{"en": "Trick Room", "es": "Espacio raro"},
		{"en": "Sacred Sword", "es": "Espada santa"},
		{"en": "Spore", "es": "Espora"},
		{"en": "Cotton spore", "es": "Esporagodón"},
		{"en": "Sketch", "es": "Esquema"},
		{"en": "Eruption", "es": "Estallido"},
		{"en": "Smelling Salts", "es": "Estímulo"},
		{"en": "Struggle Bug", "es": "Estoicismo"},
		{"en": "Boomburst", "es": "Estruendo"},
		{"en": "Wring Out", "es": "Estrujón"},
		{"en": "Dig", "es": "Excavar"},
		{"en": "Explosion", "es": "Explosión"},
		{"en": "False swipe", "es": "Falsotortazo"},
		{"en": "Rototiller", "es": "Fertilizante"},
		{"en": "Lock-on", "es": "Fijar blanco"},
		{"en": "Precipice Blades", "es": "Filo del abismo"},
		{"en": "Feint Attack", "es": "Finta"},
		{"en": "Fissure", "es": "Fisura"},
		{"en": "Focus energy", "es": "Foco energía"},
		{"en": "Flash Cannon", "es": "Foco resplandor"},
		{"en": "Seed Flare", "es": "Fogonazo"},
		{"en": "Harden", "es": "Fortaleza"},
		{"en": "Sheer cold", "es": "Frío polar"},
		{"en": "Frustration", "es": "Frustración"},
		{"en": "Will-o-wisp", "es": "Fuego fatuo"},
		{"en": "Sacred fire", "es": "Fuego sagrado"},
		{"en": "Strength", "es": "Fuerza"},
		{"en": "Superpower", "es": "Fuerza bruta"},
		{"en": "Moonblast", "es": "Fuerza lunar"},
		{"en": "Land's Wrath", "es": "Fuerza telúrica"},
		{"en": "Rage", "es": "Furia"},
		{"en": "Dragon rage", "es": "Furia dragón"},
		{"en": "Sky uppercut", "es": "Gancho alto"},
		{"en": "Crush claw", "es": "Garra brutal"},
		{"en": "Dragon claw", "es": "Garra dragón"},
		{"en": "Metal claw", "es": "Garra metal"},
		{"en": "Shadow Claw", "es": "Garra umbría"},
		{"en": "Poison gas", "es": "Gas venenoso"},
		{"en": "Geomancy", "es": "Geocontrol"},
		{"en": "Giga Impact", "es": "Giga impacto"},
		{"en": "Giga drain", "es": "Gigadrenado"},
		{"en": "Gyro Ball", "es": "Giro bola"},
		{"en": "Fire spin", "es": "Giro fuego"},
		{"en": "Rapid spin", "es": "Giro rápido"},
		{"en": "Thrash", "es": "Golpe"},
		{"en": "Aerial ace", "es": "Golpe aéreo"},
		{"en": "Sucker Punch", "es": "Golpe bajo"},
		{"en": "Dual Chop", "es": "Golpe bis"},
		{"en": "Headbutt", "es": "Golpe cabeza"},
		{"en": "Heat Crash", "es": "Golpe calor"},
		{"en": "Body slam", "es": "Golpe cuerpo"},
		{"en": "Phantom Force", "es": "Golpe fantasma"},
		{"en": "Karate chop", "es": "Golpe karate"},
		{"en": "Rock smash", "es": "Golpe roca"},
		{"en": "Shadow Force", "es": "Golpe umbrío"},
		{"en": "Fury swipes", "es": "Golpes furia"},
		{"en": "Miracle Eye", "es": "Gran ojo"},
		{"en": "Hail", "es": "Granizo"},
		{"en": "Gravity", "es": "Gravedad"},
		{"en": "Growl", "es": "Gruñido"},
		{"en": "Chip Away", "es": "Guardia baja"},
		{"en": "Guillotine", "es": "Guillotina"},
		{"en": "Trick-or-Treat", "es": "Halloween"},
		{"en": "Hydro pump", "es": "Hidrobomba"},
		{"en": "Hydro cannon", "es": "Hidrocañón"},
		{"en": "Water sport", "es": "Hidrochorro"},
		{"en": "Water pulse", "es": "Hidropulso"},
		{"en": "Grass Knot", "es": "Hierba lazo"},
		{"en": "Hyper fang", "es": "Hiper colmillo"},
		{"en": "Hyper beam", "es": "Hiperrayo"},
		{"en": "Hypnosis", "es": "Hipnosis"},
		{"en": "Razor leaf", "es": "Hoja afilada"},
		{"en": "Leaf blade", "es": "Hoja aguda"},
		{"en": "Magical leaf", "es": "Hoja mágica"},
		{"en": "Bone club", "es": "Hueso palo"},
		{"en": "Bonemerang", "es": "Huesomerang"},
		{"en": "Lava Plume", "es": "Humareda"},
		{"en": "U-turn", "es": "Ida y vuelta"},
		{"en": "Facade", "es": "Imagen"},
		{"en": "Role play", "es": "Imitación"},
		{"en": "Thunder Shock", "es": "Impactrueno"},
		{"en": "Astonish", "es": "Impresionar"},
		{"en": "Inferno", "es": "Infierno"},
		{"en": "Hex", "es": "Infortunio"},
		{"en": "Skill swap", "es": "Intercambio"},
		{"en": "Reversal", "es": "Inversión"},
		{"en": "Power Split", "es": "Isofuerza"},
		{"en": "Guard Split", "es": "Isoguardia"},
		{"en": "Power Gem", "es": "Joya de luz"},
		{"en": "Foul Play", "es": "Juego sucio"},
		{"en": "Kinesis", "es": "Kinético"},
		{"en": "Thief", "es": "Ladrón"},
		{"en": "Gunk Shot", "es": "Lanza mugre"},
		{"en": "Flamethrower", "es": "Lanzallamas"},
		{"en": "Fling", "es": "Lanzamiento"},
		{"en": "Rock throw", "es": "Lanzarrocas"},
		{"en": "Power Whip", "es": "Latigazo"},
		{"en": "Tail whip", "es": "Látigo"},
		{"en": "Vine whip", "es": "Látigo cepa"},
		{"en": "Memento", "es": "Legado"},
		{"en": "Lick", "es": "Lengüetazo"},
		{"en": "Magnet Rise", "es": "Levitón"},
		{"en": "Freeze-Dry", "es": "Liofilización"},
		{"en": "Blue Flare", "es": "Llama azul"},
		{"en": "Mystical Fire", "es": "Llama embrujada"},
		{"en": "Fusion Flare", "es": "Llama fusión"},
		{"en": "Ice Burn", "es": "Llama gélida"},
		{"en": "Fire blast", "es": "Llamarada"},
		{"en": "Fake tears", "es": "Llanto falso"},
		{"en": "Storm Throw", "es": "Llave corsé"},
		{"en": "Circle Throw", "es": "Llave giro"},
		{"en": "Leaf Storm", "es": "Lluevehojas"},
		{"en": "Magma Storm", "es": "Lluvia ígnea"},
		{"en": "Light of Ruin", "es": "Luz aniquiladora"},
		{"en": "Moonlight", "es": "Luz lunar"},
		{"en": "Hammer Arm", "es": "Machada"},
		{"en": "Magnitude", "es": "Magnitud"},
		{"en": "Mean look", "es": "Mal de ojo"},
		{"en": "Curse", "es": "Maldición"},
		{"en": "Leer", "es": "Malicioso"},
		{"en": "Hold hands", "es": "Manos juntas"},
		{"en": "Mirror coat", "es": "Manto espejo"},
		{"en": "Nasty plot", "es": "Maquinación"},
		{"en": "Crabhammer", "es": "Martillazo"},
		{"en": "Psych up", "es": "Más psique"},
		{"en": "Cosmic power", "es": "Masa cósmica"},
		{"en": "Wood Hammer", "es": "Mazazo"},
		{"en": "Meditate", "es": "Meditación"},
		{"en": "Mega drain", "es": "Megaagotar"},
		{"en": "Megahorn", "es": "Megacuerno"},
		{"en": "Mega kick", "es": "Megapatada"},
		{"en": "Mega punch", "es": "Megapuño"},
		{"en": "Weather ball", "es": "Meteorobola"},
		{"en": "Metronome", "es": "Metrónomo"},
		{"en": "Mimic", "es": "Mimético"},
		{"en": "Destiny bond", "es": "Mismodestino"},
		{"en": "Taunt", "es": "Mofa"},
		{"en": "Nuzzle", "es": "Moflete estático"},
		{"en": "Bite", "es": "Mordisco"},
		{"en": "Mirror move", "es": "Movimiento espejo"},
		{"en": "Seismic toss", "es": "Movimiento sísmico"},
		{"en": "Glaciate", "es": "Mundo gélido"},
		{"en": "Mist", "es": "Neblina"},
		{"en": "Haze", "es": "Niebla"},
		{"en": "Aromatic Mist", "es": "Niebla aromática"},
		{"en": "Clear Smog", "es": "Niebla clara"},
		{"en": "Powder snow", "es": "Nieve polvo"},
		{"en": "Flame Charge", "es": "Nitrocarga"},
		{"en": "Bestow", "es": "Ofrenda"},
		{"en": "Baby-Doll Eyes", "es": "Ojitos tiernos"},
		{"en": "Eerie Impulse", "es": "Onda anómala"},
		{"en": "Focus Blast", "es": "Onda certera"},
		{"en": "Heat wave", "es": "Onda ígnea"},
		{"en": "Psystrike", "es": "Onda mental"},
		{"en": "Simple Beam", "es": "Onda simple"},
		{"en": "Sludge Wave", "es": "Onda tóxica"},
		{"en": "Thunder wave", "es": "Onda trueno"},
		{"en": "Vacuum Wave", "es": "Onda vacío"},
		{"en": "Shock wave", "es": "Onda voltio"},
		{"en": "Encore", "es": "Otra vez"},
		{"en": "Happy Hour", "es": "Paga extra"},
		{"en": "Brave Bird", "es": "Pájaro osado"},
		{"en": "Beat Up", "es": "Paliza"},
		{"en": "Force Palm", "es": "Palmeo"},
		{"en": "Light Screen", "es": "Pantalla luz"},
		{"en": "Smokescreen", "es": "Pantallahumo"},
		{"en": "Stun Spore", "es": "Paralizador"},
		{"en": "Extrasensory", "es": "Paranormal"},
		{"en": "Hyperspace Hole", "es": "Paso dimensional"},
		{"en": "Low Kick", "es": "Patada baja"},
		{"en": "Rolling Kick", "es": "Patada giro"},
		{"en": "Blaze Kick", "es": "Patada ígnea"},
		{"en": "Jump Kick", "es": "Patada salto"},
		{"en": "High Jump Kick", "es": "Patada salto alta"},
		{"en": "Calm Mind", "es": "Paz mental"},
		{"en": "Rock Blast", "es": "Pedrada"},
		{"en": "Horn Drill", "es": "Perforador"},
		{"en": "Pursuit", "es": "Persecución"},
		{"en": "Nightmare", "es": "Pesadilla"},
		{"en": "Bug Bite", "es": "Picadura"},
		{"en": "Drill Peck", "es": "Pico taladro"},
		{"en": "Peck", "es": "Picotazo"},
		{"en": "Poison Sting", "es": "Picotazo venenoso"},
		{"en": "Pluck", "es": "Picoteo"},
		{"en": "Pin Missile", "es": "Pin misil"},
		{"en": "Flame Burst", "es": "Pirotecnia"},
		{"en": "Stomp", "es": "Pisotón"},
		{"en": "Water Gun", "es": "Pistola agua"},
		{"en": "Tackle", "es": "Placaje"},
		{"en": "Volt Tackle", "es": "Placaje eléctrico"},
		{"en": "Flying Press", "es": "Plancha voladora"},
		{"en": "Frenzy Plant", "es": "Planta feroz"},
		{"en": "Tail Slap", "es": "Plumerazo"},
		{"en": "Hidden Power", "es": "Poder oculto"},
		{"en": "Ancient Power", "es": "Poder pasado"},
		{"en": "Stored Power", "es": "Poder reserva"},
		{"en": "Smog", "es": "Polución"},
		{"en": "Powder", "es": "Polvo explosivo"},
		{"en": "Rage Powder", "es": "Polvo ira"},
		{"en": "Poison Powder", "es": "Polvo veneno"},
		{"en": "Future Sight", "es": "Premonición"},
		{"en": "Barrage", "es": "Presa"},
		{"en": "Present", "es": "Presente"},
		{"en": "Foresight", "es": "Profecía"},
		{"en": "Protect", "es": "Protección"},
		{"en": "Psycho Shift", "es": "Psicocambio"},
		{"en": "Psycho Cut", "es": "Psicocorte"},
		{"en": "Psycho Boost", "es": "Psicoataque"},
		{"en": "Psyshock", "es": "Psicocarga"},
		{"en": "Psywave", "es": "Psicoonda"},
		{"en": "Psybeam", "es": "Psicorrayo"},
		{"en": "Psychic", "es": "Psíquico"},
		{"en": "Spikes", "es": "Púas"},
		{"en": "Toxic Spikes", "es": "Púas tóxicas"},
		{"en": "Rock Polish", "es": "Pulimento"},
		{"en": "Octazooka", "es": "Pulpocañón"},
		{"en": "Heal Pulse", "es": "Pulso cura"},
		{"en": "Dragon Pulse", "es": "Pulso dragón"},
		{"en": "Night Daze", "es": "Pulso noche"},
		{"en": "Origin Pulse", "es": "Pulso primigenio"},
		{"en": "Dark Pulse", "es": "Pulso umbrío"},
		{"en": "Low Sweep", "es": "Puntapié"},
		{"en": "Bullet Punch", "es": "Puño bala"},
		{"en": "Focus Punch", "es": "Puño certero"},
		{"en": "Comet Punch", "es": "Puño cometa"},
		{"en": "Drain Punch", "es": "Puño drenaje"},
		{"en": "Fire Punch", "es": "Puño fuego"},
		{"en": "Ice Punch", "es": "Puño hielo"},
		{"en": "Power-Up Punch", "es": "Puño incremento"},
		{"en": "Dizzy Punch", "es": "Puño mareo"},
		{"en": "Meteor Mash", "es": "Puño meteoro"},
		{"en": "Shadow Punch", "es": "Puño sombra"},
		{"en": "Thunder Punch", "es": "Puño trueno"},
		{"en": "Dynamic Punch", "es": "Puñodinámico"},
		{"en": "Poison Jab", "es": "Puya nociva"},
		{"en": "Grudge", "es": "Rabia"},
		{"en": "Tail Glow", "es": "Ráfaga"},
		{"en": "Swift", "es": "Rapidez"},
		{"en": "Odor Sleuth", "es": "Rastreo"},
		{"en": "Thunderbolt", "es": "Rayo"},
		{"en": "Aurora Beam", "es": "Rayo aurora"},
		{"en": "Bubble Beam", "es": "Rayo burbuja"},
		{"en": "Charge Beam", "es": "Rayo carga"},
		{"en": "Confuse Ray", "es": "Rayo confuso"},
		{"en": "Fusion Bolt", "es": "Rayo fusión"},
		{"en": "Freeze Shock", "es": "Rayo gélido"},
		{"en": "Ice Beam", "es": "Rayo hielo"},
		{"en": "Solar Beam", "es": "Rayo solar"},
		{"en": "Recycle", "es": "Reciclaje"},
		{"en": "Recover", "es": "Recuperación"},
		{"en": "Bullet Seed", "es": "Recurrente"},
		{"en": "Minimize", "es": "Reducción"},
		{"en": "Sticky Web", "es": "Red viscosa"},
		{"en": "Reflect", "es": "Reflejo"},
		{"en": "Helping Hand", "es": "Refuerzo"},
		{"en": "Withdraw", "es": "Refugio"},
		{"en": "Slack Off", "es": "Relajo"},
		{"en": "Baton Pass", "es": "Relevo"},
		{"en": "Whirlwind", "es": "Remolino"},
		{"en": "Spite", "es": "Rencor"},
		{"en": "Metal Burst", "es": "Represión metal"},
		{"en": "Retaliate", "es": "Represalia"},
		{"en": "Stockpile", "es": "Reserva"},
		{"en": "Sludge", "es": "Residuos"},
		{"en": "Roost", "es": "Respiro"},
		{"en": "Luster Purge", "es": "Resplandor"},
		{"en": "Constrict", "es": "Restricción"},
		{"en": "Return", "es": "Retribución"},
		{"en": "Topsy-Turvy", "es": "Reversión"},
		{"en": "Cotton Guard", "es": "Rizo algodón"},
		{"en": "Defense Curl", "es": "Rizo defensa"},
		{"en": "Snatch", "es": "Robo"},
		{"en": "Stone Edge", "es": "Roca afilada"},
		{"en": "Steamroller", "es": "Rodillo de púas"},
		{"en": "Shell Smash", "es": "Rompecoraza"},
		{"en": "Rock Wrecker", "es": "Romperrocas"},
		{"en": "Snore", "es": "Ronquido"},
		{"en": "Gear Grind", "es": "Rueda doble"},
		{"en": "Flame Wheel", "es": "Rueda fuego"},
		{"en": "Roar", "es": "Rugido"},
		{"en": "Noble Roar", "es": "Rugido de guerra"},
		{"en": "Secret Sword", "es": "Sable místico"},
		{"en": "Final Gambit", "es": "Sacrificio"},
		{"en": "Brine", "es": "Salmuera"},
		{"en": "Splash", "es": "Salpicadura"},
		{"en": "Water Spout", "es": "Salpicar"},
		{"en": "Captivate", "es": "Seducción"},
		{"en": "Judgment", "es": "Sentencia"},
		{"en": "Follow Me", "es": "Señuelo"},
		{"en": "Water Shuriken", "es": "Shuriken de agua"},
		{"en": "Grass Whistle", "es": "Silbato"},
		{"en": "Synchronoise", "es": "Sincrorruido"},
		{"en": "Synthesis", "es": "Síntesis"},
		{"en": "Overheat", "es": "Sofoco"},
		{"en": "Morning Sun", "es": "Sol matinal"},
		{"en": "Shadow Sneak", "es": "Sombra vil"},
		{"en": "Sleep Powder", "es": "Somnífero"},
		{"en": "Sleep Talk", "es": "Sonámbulo"},
		{"en": "Fake Out", "es": "Sorpresa"},
		{"en": "Submission", "es": "Sumisión"},
		{"en": "Super Fang", "es": "Superdiente"},
		{"en": "Supersonic", "es": "Supersónico"},
		{"en": "Surf", "es": "Surf"},
		{"en": "Substitute", "es": "Sustituto"},
		{"en": "Air Slash", "es": "Tajo aéreo"},
		{"en": "Cross Chop", "es": "Tajo cruzado"},
		{"en": "Night Slash", "es": "Tajo umbrío"},
		{"en": "Drill Run", "es": "Taladradora"},
		{"en": "Belly Drum", "es": "Tambor"},
		{"en": "Techno Blast", "es": "Tecno shock"},
		{"en": "Spider Web", "es": "Telaraña"},
		{"en": "Mind Reader", "es": "Telépata"},
		{"en": "Telekinesis", "es": "Telequinesis"},
		{"en": "Teleport", "es": "Teletransporte"},
		{"en": "Clamp", "es": "Tenaza"},
		{"en": "Bulldoze", "es": "Terratemblor"},
		{"en": "Earthquake", "es": "Terremoto"},
		{"en": "Head Smash", "es": "Testarazo"},
		{"en": "Earth Power", "es": "Tierra viva"},
		{"en": "X-Scissor", "es": "Tijera X"},
		{"en": "Night shade", "es": "Tinieblas"},
		{"en": "Vital Throw", "es": "Tiro vital"},
		{"en": "Whirlpool", "es": "Torbellino"},
		{"en": "Sandstorm", "es": "Tormenta arena"},
		{"en": "Diamond Storm", "es": "Tormenta de diamantes"},
		{"en": "Petal Blizzard", "es": "Tormenta floral"},
		{"en": "Torment", "es": "Tormento"},
		{"en": "Gust", "es": "Tornado"},
		{"en": "Toxic", "es": "Tóxico"},
		{"en": "Swallow", "es": "Tragar"},
		{"en": "Stealth Rock", "es": "Trampa rocas"},
		{"en": "Venom Drench", "es": "Trampa venenosa"},
		{"en": "Transform", "es": "Transformación"},
		{"en": "Switcheroo", "es": "Trapicheo"},
		{"en": "Rock Climb", "es": "Treparrocas"},
		{"en": "Tri Attack", "es": "Triataque"},
		{"en": "Triple Kick", "es": "Triple patada"},
		{"en": "Crunch", "es": "Triturar"},
		{"en": "Trick", "es": "Truco"},
		{"en": "Crafty Shield", "es": "Truco defensa"},
		{"en": "Power Trick", "es": "Truco fuerza"},
		{"en": "Thunder", "es": "Trueno"},
		{"en": "Rock tomb", "es": "Tumba rocas"},
		{"en": "Last Resort", "es": "Última baza"},
		{"en": "Parting Shot", "es": "Última palabra"},
		{"en": "Quash", "es": "Último lugar"},
		{"en": "Mach Punch", "es": "Ultrapuño"},
		{"en": "V-create", "es": "V de fuego"},
		{"en": "Frost Breath", "es": "Vaho gélido"},
		{"en": "Wide Guard", "es": "Vastaguardia"},
		{"en": "Safeguard", "es": "Velo sagrado"},
		{"en": "Extreme Speed", "es": "Velocidad extrema"},
		{"en": "Hurricane", "es": "Vendaval"},
		{"en": "Payback", "es": "Vendetta"},
		{"en": "Cross Poison", "es": "Veneno X"},
		{"en": "Bide", "es": "Venganza"},
		{"en": "Blizzard", "es": "Ventisca"},
		{"en": "Ominous Wind", "es": "Viento aciago"},
		{"en": "Tailwind", "es": "Viento afín"},
		{"en": "Razor Wind", "es": "Viento cortante"},
		{"en": "Fairy Wind", "es": "Viento feérico"},
		{"en": "Icy Wind", "es": "Viento hielo"},
		{"en": "Silver Wind", "es": "Viento plata"},
		{"en": "Wild Charge", "es": "Voltio cruel"},
		{"en": "Volt Switch", "es": "Voltiocambio"},
		{"en": "Water Pledge", "es": "Voto agua"},
		{"en": "Fire Pledge", "es": "Voto fuego"},
		{"en": "Grass Pledge", "es": "Voto planta"},
		{"en": "Hyper voice", "es": "Vozarrón"},
		{"en": "Disarming Voice", "es": "Voz cautivadora"},
		{"en": "Fly", "es": "Vuelo"},
		{"en": "Me First", "es": "Yo primero"},
		{"en": "Wonder Room", "es": "Zona extraña"},
		{"en": "Magic Room", "es": "Zona mágica"},
		{"en": "Bug Buzz", "es": "Zumbido"}
	],
	"item": [
		{"en": "Abomasite", "es": "Abomasnowita"},
		{"en": "Gooey Mulch", "es": "Abono brote"},
		{"en": "TMV Pass", "es": "Abono del TMV"},
		{"en": "Rich Mulch", "es": "Abono fértil"},
		{"en": "Stable Mulch", "es": "Abono fijador"},
		{"en": "Boost Mulch", "es": "Abono fructífero"},
		{"en": "Amaze Mulch", "es": "Abono insólito"},
		{"en": "Damp Mulch", "es": "Abono lento"},
		{"en": "Growth Mulch", "es": "Abono rápido"},
		{"en": "Surprise Mulch", "es": "Abono sorpresa"},
		{"en": "Absolite", "es": "Absolita"},
		{"en": "Colress Machine", "es": "Acromáquina"},
		{"en": "Aerodactylite", "es": "Aerodactylita"},
		{"en": "Aggronite", "es": "Aggronita"},
		{"en": "Fresh Water", "es": "Agua fresca"},
		{"en": "Mystic Water", "es": "Agua mística"},
		{"en": "Alakazamite", "es": "Alakazamita"},
		{"en": "Rainbow Wing", "es": "Ala arcoíris"},
		{"en": "Silver Wing", "es": "Ala plateada"},
		{"en": "Old Amber", "es": "Ámbar viejo"},
		{"en": "Ampharosite", "es": "Ampharosita"},
		{"en": "Cleanse Tag", "es": "Amuleto"},
		{"en": "Shiny Charm", "es": "Amuleto iris "},
		{"en": "Oval Charm", "es": "Amuleto oval"},
		{"en": "Relic Vase", "es": "Ánfora"},
		{"en": "Nevermeltice", "es": "Antiderretir"},
		{"en": "Antidote", "es": "Antídoto"},
		{"en": "Ice Heal", "es": "Antihielo"},
		{"en": "Burn Heal", "es": "Antiquemar"},
		{"en": "Parlyze Heal", "es": "Antiparalizador"},
		{"en": "Soft Sand", "es": "Arena fina"},
		{"en": "X Attack", "es": "Ataque X"},
		{"en": "Binding Band", "es": "Banda atadura"},
		{"en": "Focus Sash", "es": "Banda focus"},
		{"en": "Power Band", "es": "Banda recia"},
		{"en": "Banettite", "es": "Banettita"},
		{"en": "Old Gateau", "es": "Barrita plus"},
		{"en": "Bicycle", "es": "Bicicleta"},
		{"en": "Acro Bike", "es": "Bici acrobática"},
		{"en": "Mach Bike", "es": "Bici carrera"},
		{"en": "Ring Target", "es": "Blanco"},
		{"en": "Blastoisinite", "es": "Blastoisita"},
		{"en": "Blazikenite", "es": "Blazikenita"},
		{"en": "Pal Pad", "es": "Bloc amigos"},
		{"en": "Unown Report", "es": "Bloc Unown"},
		{"en": "Snowball", "es": "Bola de nieve"},
		{"en": "Iron Ball", "es": "Bola férrea"},
		{"en": "Smoke Ball", "es": "Bola humo"},
		{"en": "Light Ball", "es": "Bolaluminosa"},
		{"en": "Looker Ticket", "es": "Boleto Handsome"},
		{"en": "Seal Bag", "es": "Bolsa sellos"},
		{"en": "Bike Voucher", "es": "Bono bici"},
		{"en": "Powder Jar", "es": "Bote polvos"},
		{"en": "Eject button", "es": "Botón escape"},
		{"en": "Relic Band", "es": "Brazal"},
		{"en": "Macho Brace", "es": "Brazal firme"},
		{"en": "Power Bracer", "es": "Brazal recio"},
		{"en": "Vs. Seeker", "es": "Buscapelea"},
		{"en": "Red Chain", "es": "Cadena roja"},
		{"en": "Apricorn Box", "es": "Caja bonguri"},
		{"en": "Fashion Case", "es": "Caja corazón"},
		{"en": "Medal Box", "es": "Caja de insignias"},
		{"en": "Seal Case", "es": "Caja sellos"},
		{"en": "Calcium", "es": "Calcio"},
		{"en": "Good Rod", "es": "Caña buena"},
		{"en": "Old Rod", "es": "Caña vieja"},
		{"en": "Vs. Recorder", "es": "Cámara lucha"},
		{"en": "Soothe Bell", "es": "Campana alivio"},
		{"en": "Clear Bell", "es": "Campana clara"},
		{"en": "Shell Bell", "es": "Campana concha"},
		{"en": "Tidal Bell", "es": "Campana oleaje"},
		{"en": "Lock Capsule", "es": "Cápsula candado"},
		{"en": "Rare Candy", "es": "Caramelo raro"},
		{"en": "Carbos", "es": "Carburante"},
		{"en": "Charcoal", "es": "Carbón"},
		{"en": "Relic crown", "es": "Corona antigua"},
		{"en": "Member Card", "es": "Carné socio"},
		{"en": "Letter", "es": "Carta"},
		{"en": "Steel Mail", "es": "Carta acero"},
		{"en": "Air Mail", "es": "Carta aérea"},
		{"en": "Glitter Mail", "es": "Carta brillo"},
		{"en": "Heart Mail", "es": "Carta corazón"},
		{"en": "Fabulous Mail", "es": "Carta fabulosa"},
		{"en": "Flower Mail", "es": "Carta flores"},
		{"en": "Flame Mail", "es": "Carta fuego"},
		{"en": "Grass Mail", "es": "Carta hierba"},
		{"en": "Bead Mail", "es": "Carta imagen"},
		{"en": "Mech Mail", "es": "Carta imán"},
		{"en": "Wood Mail", "es": "Carta madera"},
		{"en": "Tunnel Mail", "es": "Carta mina"},
		{"en": "Mosaic Mail", "es": "Carta mosaico"},
		{"en": "Orange Mail", "es": "Carta naranja"},
		{"en": "Snow Mail", "es": "Carta nieve"},
		{"en": "Wave Mail", "es": "Carta ola"},
		{"en": "Brick Mail", "es": "Carta pared"},
		{"en": "Bubble Mail", "es": "Carta pompas"},
		{"en": "Prof's Letter", "es": "Carta profesor"},
		{"en": "Oak's Letter", "es": "Carta pr. Oak"},
		{"en": "Harbor Mail", "es": "Carta puerto"},
		{"en": "Retro Mail", "es": "Carta retro"},
		{"en": "Space Mail", "es": "Carta sideral"},
		{"en": "Shadow Mail", "es": "Carta sombra"},
		{"en": "Dream Mail", "es": "Carta sueño"},
		{"en": "Tropic Mail", "es": "Carta tropical"},
		{"en": "Rocky Helmet", "es": "Casco dentado"},
		{"en": "Assault Vest", "es": "Chaleco asalto"},
		{"en": "Charizardite X", "es": "Charizardita X"},
		{"en": "Charizardite Y", "es": "Charizardita Y"},
		{"en": "Sacred Ash", "es": "Ceniza sagrada"},
		{"en": "Choice Band", "es": "Cinta elegida"},
		{"en": "Black Belt", "es": "Cinturón negro"},
		{"en": "Focus Band", "es": "Cinta focus"},
		{"en": "Muscle Band", "es": "Cinta fuerte"},
		{"en": "Expert Belt", "es": "Cinta experto"},
		{"en": "Power Belt", "es": "Cinto recio"},
		{"en": "Lagging Tail", "es": "Cola plúmbea"},
		{"en": "Fluffy Tail", "es": "Cola Skitty"},
		{"en": "Slowpoke Tail", "es": "Cola Slowpoke"},
		{"en": "Razor Fang", "es": "Colmillagudo"},
		{"en": "Dragon Fang", "es": "Colmillo dragón"},
		{"en": "Shoal Shell", "es": "Concha cardumen"},
		{"en": "Sweet Heart", "es": "Corazón dulce"},
		{"en": "Oak's Parcel", "es": "Correo Oak"},
		{"en": "Dragon Bone", "es": "Cráneo dragón"},
		{"en": "Lumiose Galette", "es": "Crêpe Luminalia"},
		{"en": "Chill Drive", "es": "CrioROM"},
		{"en": "Wailmer Pail", "es": "Cubo Wailmer"},
		{"en": "Twistedspoon", "es": "Cuchara torcida"},
		{"en": "Escape Rope", "es": "Cuerda huida"},
		{"en": "Coupon 1", "es": "Cupón 1"},
		{"en": "Coupon 2", "es": "Cupón 2"},
		{"en": "Coupon 3", "es": "Cupón 3"},
		{"en": "Full Heal", "es": "Cura total"},
		{"en": "X Special Defend", "es": "Defensa especial X"},
		{"en": "X Defend", "es": "Defensa X"},
		{"en": "Awakening", "es": "Despertar"},
		{"en": "Devon Scope", "es": "Detector Devon"},
		{"en": "Adamant Orb", "es": "Diamansfera"},
		{"en": "Journal", "es": "Diario"},
		{"en": "Deepseatooth", "es": "Diente marino"},
		{"en": "Gold Teeth", "es": "Dientes oro"},
		{"en": "Dubious Disc", "es": "Disco extraño"},
		{"en": "Dire Hit", "es": "Directo"},
		{"en": "Whipped Dream", "es": "Dulce de nata"},
		{"en": "Electrizer", "es": "Electrizador"},
		{"en": "Elixir", "es": "Elixir"},
		{"en": "Max Elixir", "es": "Elixir máximo"},
		{"en": "Honor of Kalos", "es": "Emblema Kalos"},
		{"en": "Gram", "es": "Envío (x3)"},
		{"en": "Prism Scale", "es": "Escama bella"},
		{"en": "Heart Scale", "es": "Escama corazón"},
		{"en": "Deepseascale", "es": "Escama marina"},
		{"en": "Red Scale", "es": "Escama roja"},
		{"en": "Dragon Scale", "es": "Escamadragón"},
		{"en": "Scanner", "es": "Escáner"},
		{"en": "Green Orb", "es": "Esfera verde"},
		{"en": "Relic Statue", "es": "Efigie antigua"},
		{"en": "X Special", "es": "Especial X"},
		{"en": "Reveal Glass", "es": "Espejo veraz"},
		{"en": "Strange Souvenir", "es": "Estatuilla rara"},
		{"en": "Ether", "es": "Éter"},
		{"en": "Yellow Flute", "es": "Flauta amarilla"},
		{"en": "Blue Flute", "es": "Flauta azul"},
		{"en": "White Flute", "es": "Flauta blanca"},
		{"en": "Black Flute", "es": "Flauta negra"},
		{"en": "Red Flute", "es": "Flauta roja"},
		{"en": "Azure Flute", "es": "Flauta azur"},
		{"en": "Poison Barb", "es": "Flecha venenosa"},
		{"en": "Comet Shard", "es": "Fragmento cometa"},
		{"en": "Power Ankle", "es": "Franja recia"},
		{"en": "Sail Fossil", "es": "Fósil aleta"},
		{"en": "Armor Fossil", "es": "Fósil coraza"},
		{"en": "Skull Fossil", "es": "Fósil cráneo"},
		{"en": "Dome Fossil", "es": "Fósil domo"},
		{"en": "Claw Fossil", "es": "Fósil garra"},
		{"en": "Helix Fossil", "es": "Fósil hélix"},
		{"en": "Jaw Fossil", "es": "Fósil mandíbula"},
		{"en": "Plume Fossil", "es": "Fósil pluma"},
		{"en": "Root Fossil", "es": "Fósil raíz"},
		{"en": "Cover Fossil", "es": "Fósil tapa"},
		{"en": "Shock Drive", "es": "FulgoROM"},
		{"en": "Safety Goggles", "es": "Gafa protectora"},
		{"en": "Go-Goggles", "es": "Gafas aislantes"},
		{"en": "BlackGlasses", "es": "Gafas de sol"},
		{"en": "Choice Specs", "es": "Gafas elegid"},
		{"en": "Wise Glasses", "es": "Gafas especiales"},
		{"en": "Lava Cookie", "es": "Galleta lava"},
		{"en": "Garchompite", "es": "Garchompita"},
		{"en": "Gardevoirite", "es": "Gardevoirita"},
		{"en": "Grip Claw", "es": "Garra garfio"},
		{"en": "Quick Claw", "es": "Garra rápida"},
		{"en": "Razor Claw", "es": "Garra afilada"},
		{"en": "Steel Gem", "es": "Gema acero"},
		{"en": "Water Gem", "es": "Gema agua"},
		{"en": "Bug Gem", "es": "Gema bicho"},
		{"en": "Dragon Gem", "es": "Gema dragón"},
		{"en": "Electric Gem", "es": "Gema eléctrica"},
		{"en": "Ghost Gem", "es": "Gema fantasma"},
		{"en": "Fire Gem", "es": "Gema fuego"},
		{"en": "Ice Gem", "es": "Gema hielo"},
		{"en": "Fighting Gem", "es": "Gema lucha"},
		{"en": "Normal Gem", "es": "Gema normal"},
		{"en": "Grass Gem", "es": "Gema planta"},
		{"en": "Psychic Gem", "es": "Gema psíquica"},
		{"en": "Rock Gem", "es": "Gema roca"},
		{"en": "Dark Gem", "es": "Gema siniestra"},
		{"en": "Ground Gem", "es": "Gema tierra"},
		{"en": "Poison Gem", "es": "Gema veneno"},
		{"en": "Flying Gem", "es": "Gema voladora"},
		{"en": "Berserk Gene", "es": "Gen loco"},
		{"en": "Gengarite", "es": "Gengarita"},
		{"en": "Air balloon", "es": "Globo helio"},
		{"en": "Gracidea", "es": "Gracídea"},
		{"en": "Griseous Orb", "es": "Griseosfera"},
		{"en": "Adventure Rules", "es": "Guía de máximas"},
		{"en": "Gyaradosite", "es": "Gyaradosita"},
		{"en": "Spell Tag", "es": "Hechizo"},
		{"en": "Heracrossite", "es": "Heracrossita"},
		{"en": "Douse Drive", "es": "HidroROM"},
		{"en": "White Herb", "es": "Hierba blanca"},
		{"en": "Mental Herb", "es": "Hierba mental"},
		{"en": "Power Herb", "es": "Hierba única"},
		{"en": "Revival Herb", "es": "Hierba revivir"},
		{"en": "Iron", "es": "Hierro"},
		{"en": "Hyper Potion", "es": "Hiperpoción"},
		{"en": "Holo Caster", "es": "Holomisor"},
		{"en": "Houndoomite", "es": "Houndoomita"},
		{"en": "Thick Club", "es": "Hueso grueso"},
		{"en": "Rare Bone", "es": "Hueso raro"},
		{"en": "Mystery Egg", "es": "Huevo misterioso"},
		{"en": "Lucky Egg", "es": "Huevo suerte"},
		{"en": "Kangaskhanite", "es": "Kangaskhanita"},
		{"en": "Magnet", "es": "Imán"},
		{"en": "Wave Incense", "es": "Incienso aqua"},
		{"en": "Luck Incense", "es": "Incienso duplo"},
		{"en": "Rose Incense", "es": "Incienso floral"},
		{"en": "Full Incense", "es": "Incienso lento"},
		{"en": "Sea Incense", "es": "Incienso marino"},
		{"en": "Pure Incense", "es": "Incienso puro"},
		{"en": "Odd Incense", "es": "Incienso raro"},
		{"en": "Rock Incense", "es": "Incienso roca"},
		{"en": "Lax Incense", "es": "Incienso suave"},
		{"en": "Rainbow Pass", "es": "Iris-Ticket"},
		{"en": "Explorer Kit", "es": "Kit de exploración"},
		{"en": "Brick Piece", "es": "Ladrillo"},
		{"en": "Destiny Knot", "es": "Lazo destino"},
		{"en": "Pink Bow", "es": "Lazo rosa"},
		{"en": "Moomoo Milk", "es": "Leche Mu-mu"},
		{"en": "GB Sounds", "es": "Lector GB"},
		{"en": "Power Lens", "es": "Lente recia"},
		{"en": "Lemonade", "es": "Limonada"},
		{"en": "Flame Orb", "es": "Llamasfera"},
		{"en": "Storage Key", "es": "Llave almacén"},
		{"en": "Storage Key", "es": "Llave almacén"},
		{"en": "Lift Key", "es": "Llave ascensor"},
		{"en": "Elevator Key", "es": "Llave ascensor"},
		{"en": "Rm. 1 Key", "es": "Llave cabina 1"},
		{"en": "Rm. 2 Key", "es": "Llave cabina 2"},
		{"en": "Rm. 4 Key", "es": "Llave cabina 4"},
		{"en": "Rm. 6 Key", "es": "Llave cabina 6"},
		{"en": "Works Key", "es": "Llave central"},
		{"en": "Galactic Key", "es": "Llave galaxia"},
		{"en": "Card Key", "es": "Llave magnética"},
		{"en": "Card Key", "es": "Llave magnética"},
		{"en": "Secret Key", "es": "Llave secreta"},
		{"en": "Secret Key", "es": "Llave secreta"},
		{"en": "Basement Key", "es": "Llave sótano"},
		{"en": "Basement Key", "es": "Llave sótano"},
		{"en": "Suite Key", "es": "Llave suite"},
		{"en": "Black Sludge", "es": "Lodo negro"},
		{"en": "Sprinklotad", "es": "Lotadgadera"},
		{"en": "Lucarionite", "es": "Lucarita"},
		{"en": "Wide Lens", "es": "Lupa"},
		{"en": "Lustrous Orb", "es": "Lustresfera"},
		{"en": "Magmarizer", "es": "Magmatizador"},
		{"en": "Manectite", "es": "Manectricita"},
		{"en": "Old Sea Map", "es": "Mapa viejo"},
		{"en": "Machine Part", "es": "Maquinaria"},
		{"en": "PP Up", "es": "Más PP"},
		{"en": "HP Up", "es": "Más PS"},
		{"en": "Max Potion", "es": "Poción máxima"},
		{"en": "Max Ether", "es": "Éter máximo"},
		{"en": "PP Max", "es": "PP máximos"},
		{"en": "Max Repel", "es": "Repelente máximo"},
		{"en": "Max Revive", "es": "Revivir máximo"},
		{"en": "Big Nugget", "es": "Maxipepita"},
		{"en": "Medichamite", "es": "Medichamita"},
		{"en": "Mega Ring", "es": "Mega-Aro"},
		{"en": "Up-Grade", "es": "Mejora"},
		{"en": "Fame checker", "es": "Memorín"},
		{"en": "Meteorite", "es": "Meteorito"},
		{"en": "Metronome", "es": "Metrónomo"},
		{"en": "Mewtwonite X", "es": "Mewtwoita X"},
		{"en": "Mewtwonite Y", "es": "Mewtwoita Y"},
		{"en": "Honey", "es": "Miel"},
		{"en": "Eviolite", "es": "Mineral evolutivo"},
		{"en": "Tinymushroom", "es": "Mini seta"},
		{"en": "Enigma Stone", "es": "Misticristal"},
		{"en": "Mystic Ticket", "es": "Misti-Ticket"},
		{"en": "Amulet Coin", "es": "Moneda amuleto"},
		{"en": "Coin Case", "es": "Monedero"},
		{"en": "Shed Shell", "es": "Muda concha"},
		{"en": "Luminous Moss", "es": "Musgo brillante"},
		{"en": "Light Stone", "es": "Orbe claro"},
		{"en": "Dark stone", "es": "Orbe oscuro"},
		{"en": "Aurora Ticket", "es": "Ori-Ticket"},
		{"en": "Choice Scarf", "es": "Pañuelo elegido"},
		{"en": "Stick", "es": "Palo"},
		{"en": "Yellow Scarf", "es": "Pañuelo amarillo"},
		{"en": "Green Scarf", "es": "Pañuelo verde"},
		{"en": "Blue Scarf", "es": "Pañuelo azul"},
		{"en": "Red Scarf", "es": "Pañuelo rojo"},
		{"en": "Pink Scarf", "es": "Pañuelo rosa"},
		{"en": "Silk Scarf", "es": "Pañuelo seda"},
		{"en": "Grubby Hanky", "es": "Pañuelo sucio"},
		{"en": "Parcel", "es": "Paquete"},
		{"en": "Yellow Shard", "es": "Parte amarilla"},
		{"en": "Blue Shard", "es": "Parte azul"},
		{"en": "Red Shard", "es": "Parte roja"},
		{"en": "Green Shard", "es": "Parte verde"},
		{"en": "License", "es": "Pase"},
		{"en": "Power Plant Pass", "es": "Pase central"},
		{"en": "Pass", "es": "Magnetopase"},
		{"en": "Contest Pass", "es": "Pase concurso"},
		{"en": "Roller Skates", "es": "Patines"},
		{"en": "Nugget", "es": "Pepita"},
		{"en": "Scope Lens", "es": "Periscopio"},
		{"en": "Pearl", "es": "Perla"},
		{"en": "Big Pearl", "es": "Perla grande"},
		{"en": "Power Weight", "es": "Pesa recia"},
		{"en": "Sharp Beak", "es": "Pico afilado"},
		{"en": "Water Stone", "es": "Piedra agua"},
		{"en": "Dawn Stone", "es": "Piedra alba"},
		{"en": "Shiny Stone", "es": "Piedra día"},
		{"en": "God Stone", "es": "Piedra dios"},
		{"en": "Hard Stone", "es": "Piedra dura"},
		{"en": "Odd Keystone", "es": "Piedra espíritu"},
		{"en": "Fire Stone", "es": "Piedra fuego"},
		{"en": "Leaf Stone", "es": "Piedra hoja"},
		{"en": "Intriguing Stone", "es": "Piedra insólita"},
		{"en": "Moon Stone", "es": "Piedra lunar"},
		{"en": "Magma Rock", "es": "Piedra magma"},
		{"en": "Dusk Stone", "es": "Piedra noche"},
		{"en": "Oval Stone", "es": "Piedra oval"},
		{"en": "Float Stone", "es": "Piedra pómez"},
		{"en": "Sun Stone", "es": "Piedra solar"},
		{"en": "Everstone", "es": "Piedra eterna"},
		{"en": "Thunderstone", "es": "Piedra trueno"},
		{"en": "Devon Goods", "es": "Piezas Devon"},
		{"en": "Cell Battery", "es": "Pila"},
		{"en": "Pinsirite", "es": "Pinsirita"},
		{"en": "Burn Drive", "es": "PiroROM"},
		{"en": "Berry Pots", "es": "Plantabayas"},
		{"en": "Resist Wing", "es": "Pluma aguante"},
		{"en": "Pretty Wing", "es": "Pluma bella"},
		{"en": "Swift Wing", "es": "Pluma ímpetu"},
		{"en": "Genius Wing", "es": "Pluma intelecto"},
		{"en": "Lunar Wing", "es": "Pluma lunar"},
		{"en": "Clever Wing", "es": "Pluma mente"},
		{"en": "Muscle Wing", "es": "Pluma músculo"},
		{"en": "Health Wing", "es": "Pluma vigor"},
		{"en": "Potion", "es": "Poción"},
		{"en": "Secret Potion", "es": "Poción secreta"},
		{"en": "Poffin Case", "es": "Pokochera"},
		{"en": "Poké Flute", "es": "Poké flauta"},
		{"en": "Poké Doll", "es": "Poké muñeco"},
		{"en": "Poké Radar", "es": "Pokéradar"},
		{"en": "Poke-toy", "es": "Pokéseñuelo"},
		{"en": "Teachy TV", "es": "Poké Tele"},
		{"en": "Heal Powder", "es": "Polvo curación"},
		{"en": "Brightpowder", "es": "Polvo brillo"},
		{"en": "Silverpowder", "es": "Polvo plata"},
		{"en": "Energypowder", "es": "Polvoenergía"},
		{"en": "Stardust", "es": "Polvoestelar"},
		{"en": "Metal Powder", "es": "Polvo metálico"},
		{"en": "Quick Powder", "es": "Polvo veloz"},
		{"en": "Casteliacone", "es": "Porcehelado"},
		{"en": "Lens Case", "es": "Portalentillas"},
		{"en": "X Accuracy", "es": "Precisión X"},
		{"en": "Guard Spec.", "es": "Protección especial"},
		{"en": "Protector", "es": "Protector"},
		{"en": "Protein", "es": "Proteína"},
		{"en": "Sprayduck", "es": "Psydugadera"},
		{"en": "DNA Splicers", "es": "Punta ADN"},
		{"en": "Lucky Punch", "es": "Puño suerte"},
		{"en": "Energy Root", "es": "Raíz energía"},
		{"en": "Big Root", "es": "Raíz grande"},
		{"en": "Relic copper", "es": "Real cobre"},
		{"en": "Relic silver", "es": "Real plata"},
		{"en": "Relic gold", "es": "Real oro"},
		{"en": "Light Clay", "es": "Refleluz"},
		{"en": "Soda Pop", "es": "Refresco"},
		{"en": "SquirtBottle", "es": "Regadera"},
		{"en": "Pass Orbs", "es": "Regalosfera"},
		{"en": "Rule Book", "es": "Reglamento"},
		{"en": "Exp. Share", "es": "Repartir experiencia"},
		{"en": "Repel", "es": "Repelente"},
		{"en": "Full Restore", "es": "Restaurar todo"},
		{"en": "Leftovers", "es": "Restos"},
		{"en": "Metal Coat", "es": "Rev. metálico"},
		{"en": "Revive", "es": "Revivir"},
		{"en": "King's Rock", "es": "Roca del rey"},
		{"en": "Icy Rock", "es": "Roca helada"},
		{"en": "Damp Rock", "es": "Roca lluvia"},
		{"en": "Heat Rock", "es": "Roca calor"},
		{"en": "Smooth Rock", "es": "Roca suave"},
		{"en": "Soul Dew", "es": "Rocío bondad"},
		{"en": "Ruby", "es": "Rubí"},
		{"en": "Loot Sack", "es": "Saca botín"},
		{"en": "Berry Pouch", "es": "Saco bayas"},
		{"en": "Soot Sack", "es": "Saco hollín"},
		{"en": "Sachet", "es": "Saquito fragante"},
		{"en": "Shoal Salt", "es": "Sal cardumen"},
		{"en": "Pearl String", "es": "Sarta perlas"},
		{"en": "Scizorite", "es": "Scizorita"},
		{"en": "Silph Scope", "es": "Scope Silph"},
		{"en": "Weakness Policy", "es": "Seguro debilidad"},
		{"en": "Miracle Seed", "es": "Semilla milagro"},
		{"en": "BalmMushroom", "es": "Seta aroma"},
		{"en": "Big Mushroom", "es": "Seta grande"},
		{"en": "Magma Emblem", "es": "Signo Magma"},
		{"en": "Super Rod", "es": "Supercaña"},
		{"en": "Super Potion", "es": "Superpoción"},
		{"en": "Super Repel", "es": "Superrepelente"},
		{"en": "Iron Plate", "es": "Tabla acero"},
		{"en": "Insect Plate", "es": "Tabla bicho"},
		{"en": "Sky Plate", "es": "Tabla cielo"},
		{"en": "Draco Plate", "es": "Tabla draco"},
		{"en": "Pixie Plate", "es": "Tabla duende"},
		{"en": "Fist Plate", "es": "Tabla fuerte"},
		{"en": "Icicle Plate", "es": "Tabla helada"},
		{"en": "Splash Plate", "es": "Tabla linfa"},
		{"en": "Flame Plate", "es": "Tabla llama"},
		{"en": "Dread Plate", "es": "Tabla oscura"},
		{"en": "Stone Plate", "es": "Tabla pétrea"},
		{"en": "Meadow Plate", "es": "Tabla pradal"},
		{"en": "Earth Plate", "es": "Tabla terrax"},
		{"en": "Spooky Plate", "es": "Tabla terror"},
		{"en": "Toxic Plate", "es": "Tabla tóxica"},
		{"en": "Zap Plate", "es": "Tabla trueno"},
		{"en": "Mind Plate", "es": "Tabla mental"},
		{"en": "Old Charm", "es": "Talismán"},
		{"en": "Blue Card", "es": "Tarjeta azul"},
		{"en": "Data Card", "es": "Tarjeta de datos"},
		{"en": "Plasma Card", "es": "Tarjeta Plasma"},
		{"en": "Point Card", "es": "Tarjeta puntos"},
		{"en": "Red Card", "es": "Tarjeta roja"},
		{"en": "Tea", "es": "Té"},
		{"en": "Reaper Cloth", "es": "Tela terrible"},
		{"en": "Zoom Lens", "es": "Telescopio"},
		{"en": "S.S. Ticket", "es": "Ticket barco"},
		{"en": "Eon Ticket", "es": "Ticket eón"},
		{"en": "Liberty Pass", "es": "Ticket libertad"},
		{"en": "Egg Ticket", "es": "Ticket huevo"},
		{"en": "Sticky Barb", "es": "Toxiestrella"},
		{"en": "Toxic Orb", "es": "Toxisfera"},
		{"en": "Tri-Pass", "es": "Tri-Ticket"},
		{"en": "Star Piece", "es": "Trozo estrella"},
		{"en": "Absorb Bulb", "es": "Tubérculo"},
		{"en": "TM Case", "es": "Tubo MT/MO"},
		{"en": "Pokéblock Case", "es": "Tubo pokécubos"},
		{"en": "Tyranitarite", "es": "Tyranitarita"},
		{"en": "Discount Coupon", "es": "Vale descuento"},
		{"en": "X Speed", "es": "Velocidad X"},
		{"en": "Venusaurite", "es": "Venusaurita"},
		{"en": "Life Orb", "es": "Vidasfera"},
		{"en": "Xtransceiver", "es": "Videomisor"},
		{"en": "Sapphire", "es": "Zafiro"},
		{"en": "Zinc", "es": "Zinc"},
		{"en": "Berry Juice", "es": "Zumo de baya"}
	],
	"berry": [
		{"en": "Cheri Berry", "es": "Baya Zreza"},
		{"en": "Chesto Berry", "es": "Baya Atania"},
		{"en": "Pecha Berry", "es": "Baya Meloc"},
		{"en": "Rawst Berry", "es": "Baya Safre"},
		{"en": "Aspear Berry", "es": "Baya Perasi"},
		{"en": "Leppa Berry", "es": "Baya Zanama"},
		{"en": "Oran Berry", "es": "Baya Aranja"},
		{"en": "Persim Berry", "es": "Baya Caquic"},
		{"en": "Lum Berry", "es": "Baya Ziuela"},
		{"en": "Sitrus Berry", "es": "Baya Zidra"},
		{"en": "Figy Berry", "es": "Baya Higog"},
		{"en": "Wiki Berry", "es": "Baya Wiki"},
		{"en": "Mago Berry", "es": "Baya Ango"},
		{"en": "Aguav Berry", "es": "Baya Guaya"},
		{"en": "Iapapa Berry", "es": "Baya Pabaya"},
		{"en": "Razz Berry", "es": "Baya Frambu"},
		{"en": "Bluk Berry", "es": "Baya Oram"},
		{"en": "Nanab Berry", "es": "Baya Latano"},
		{"en": "Wepear Berry", "es": "Baya Peragu"},
		{"en": "Pinap Berry", "es": "Baya Pinia"},
		{"en": "Pomeg Berry", "es": "Baya Grana"},
		{"en": "Kelpsy Berry", "es": "Baya Algama"},
		{"en": "Qualot Berry", "es": "Baya Ispero"},
		{"en": "Hondew Berry", "es": "Baya Meluce"},
		{"en": "Grepa Berry", "es": "Baya Uvav"},
		{"en": "Tamato Berry", "es": "Baya Tamate"},
		{"en": "Cornn Berry", "es": "Baya Mais"},
		{"en": "Magost Berry", "es": "Baya Aostan"},
		{"en": "Rabuta Berry", "es": "Baya Rautan"},
		{"en": "Nomel Berry", "es": "Baya Monli"},
		{"en": "Spelon Berry", "es": "Baya Wikano"},
		{"en": "Pamtre Berry", "es": "Baya Plama"},
		{"en": "Watmel Berry", "es": "Baya Sambia"},
		{"en": "Durin Berry", "es": "Baya Rudion"},
		{"en": "Belue Berry", "es": "Baya Andano"},
		{"en": "Liechi Berry", "es": "Baya Lichi"},
		{"en": "Ganlon Berry", "es": "Baya Gonlan"},
		{"en": "Salac Berry", "es": "Baya Aslac"},
		{"en": "Petaya Berry", "es": "Baya Yapati"},
		{"en": "Apicot Berry", "es": "Baya Aricoc"},
		{"en": "Lansat Berry", "es": "Baya Zonlan"},
		{"en": "Starf Berry", "es": "Baya Arabol"},
		{"en": "Enigma Berry", "es": "Baya Enigma"},
		{"en": "Kacha Berry", "es": "Baya Pumkin"},
		{"en": "Booka Berry", "es": "Baya Drash"},
		{"en": "Bisuna Berry", "es": "Baya Eggant"},
		{"en": "Edoma Berry", "es": "Baya Strib"},
		{"en": "Hozu Berry", "es": "Baya Chilan"},
		{"en": "Rakka Berry", "es": "Baya Nutpea"},
		{"en": "Ginema Berry", "es": "Baya Ginema"},
		{"en": "Kuo Berry", "es": "Baya Kuo"},
		{"en": "Yago Berry", "es": "Baya Yago"},
		{"en": "Touga Berry", "es": "Baya Touga"},
		{"en": "Niniku Berry", "es": "Baya Niniku"},
		{"en": "Topo Berry", "es": "Baya Topo"},
		{"en": "Cheri Berry", "es": "Baya Zreza"},
		{"en": "Occa Berry", "es": "Baya Caoca"},
		{"en": "Passho Berry", "es": "Baya Pasio"},
		{"en": "Wacan Berry", "es": "Baya Gualot"},
		{"en": "Rindo Berry", "es": "Baya Tamar"},
		{"en": "Yache Berry", "es": "Baya Rimoya"},
		{"en": "Chople Berry", "es": "Baya Pomaro"},
		{"en": "Kebia Berry", "es": "Baya Kebia"},
		{"en": "Shuca Berry", "es": "Baya Acardo"},
		{"en": "Coba Berry", "es": "Baya Kouba"},
		{"en": "Payapa Berry", "es": "Baya Payapa"},
		{"en": "Tanga Berry", "es": "Baya Yecana"},
		{"en": "Charti Berry", "es": "Baya Alcho"},
		{"en": "Kasib Berry", "es": "Baya Drasi"},
		{"en": "Haban Berry", "es": "Baya Anjiro"},
		{"en": "Colbur Berry", "es": "Baya Dillo"},
		{"en": "Babiri Berry", "es": "Baya Baribá"},
		{"en": "Chilan Berry", "es": "Baya Chilan"},
		{"en": "Micle Berry", "es": "Baya Lagro"},
		{"en": "Custap Berry", "es": "Baya Chiri"},
		{"en": "Jaboca Berry", "es": "Baya Jaboca"},
		{"en": "Rowap Berry", "es": "Baya Magua"},
		{"en": "Roseli Berry", "es": "Baya Hibis"},
		{"en": "Maranga Berry", "es": "Baya Maranga"},
		{"en": "Kee Berry", "es": "Baya Biglia"}
	],
	"nature": [
		{"en": "Adamant", "es": "Firme"},
		{"en": "Bashful", "es": "Tímida"},
		{"en": "Bold", "es": "Osada"},
		{"en": "Brave", "es": "Audaz"},
		{"en": "Calm", "es": "Serena"},
		{"en": "Careful", "es": "Cauta"},
		{"en": "Docile", "es": "Dócil"},
		{"en": "Gentle", "es": "Amable"},
		{"en": "Hardy", "es": "Fuerte"},
		{"en": "Hasty", "es": "Activa"},
		{"en": "Impish", "es": "Agitada"},
		{"en": "Jolly", "es": "Alegre"},
		{"en": "Lax", "es": "Floja"},
		{"en": "Lonely", "es": "Huraña"},
		{"en": "Mild", "es": "Afable"},
		{"en": "Modest", "es": "Modesta"},
		{"en": "Naive", "es": "Ingenua"},
		{"en": "Naughty", "es": "Pícara"},
		{"en": "Quiet", "es": "Mansa"},
		{"en": "Quirky", "es": "Rara"},
		{"en": "Rash", "es": "Alocada"},
		{"en": "Relaxed", "es": "Plácida"},
		{"en": "Sassy", "es": "Grosera"},
		{"en": "Serious", "es": "Seria"},
		{"en": "Timid", "es": "Miedosa"}
	]
};

exports.commands = {
	trad: function(arg, by, room, cmd) {
		try {
			var trad = exports.trad;
			var aliases = require('./../data/aliases.js').BattleAliases;
		} catch (e) {
			return this.restrictReply('Se ha encontrado un error: Vuelve a probar en unos segundos.', 'pokemon');
		}
		
		var word = toId(arg);
		if (word === "") return this.restrictReply("¿Que tengo que traducir?", 'pokemon');
		if (aliases[word]) word = toId(aliases[word]);
		
		var results = [];
		
		for (var i in trad) {
			for (var j in trad[i]) {
				if (toId(trad[i][j].es) === word) results.push({"trad": trad[i][j].en, "cat": i});
				if (toId(trad[i][j].en) === word) results.push({"trad": trad[i][j].es, "cat": i});
			}
		}
		
		if (results.length) {
			if (results.length === 1) return this.restrictReply(results[0].trad, 'pokemon');
			var resultstext = "";
			for (var k in results) {
				resultstext += results[k].trad + " (" + results[k].cat + ")";
				if (k < results.length - 1) resultstext += ", ";
			}
			return this.restrictReply(resultstext, 'pokemon');
		}
		return this.restrictReply("No se ha encontrado el objeto, movimiento, habilidad o naturaleza. Recuerde escribir las tildes en las palabras en Español.", 'pokemon');
	}
};

